# Classic style by ocornut from ImThemes
alpha = 1.0
disabledAlpha = 0.6
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(229, 229, 229, 1.0)"
TextDisabled = "rgba(153, 153, 153, 1.0)"
WindowBg = "rgba(0, 0, 0, 0.85)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(28, 28, 35, 0.92)"
Border = "rgba(127, 127, 127, 0.5)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(109, 109, 109, 0.39)"
FrameBgHovered = "rgba(119, 119, 175, 0.4)"
FrameBgActive = "rgba(107, 104, 163, 0.69)"
TitleBg = "rgba(68, 68, 137, 0.83)"
TitleBgActive = "rgba(81, 81, 160, 0.87)"
TitleBgCollapsed = "rgba(102, 102, 204, 0.2)"
MenuBarBg = "rgba(102, 102, 140, 0.8)"
ScrollbarBg = "rgba(51, 63, 76, 0.6)"
ScrollbarGrab = "rgba(102, 102, 204, 0.3)"
ScrollbarGrabHovered = "rgba(102, 102, 204, 0.4)"
ScrollbarGrabActive = "rgba(104, 99, 204, 0.6)"
CheckMark = "rgba(229, 229, 229, 0.5)"
SliderGrab = "rgba(255, 255, 255, 0.3)"
SliderGrabActive = "rgba(104, 99, 204, 0.6)"
Button = "rgba(89, 102, 155, 0.62)"
ButtonHovered = "rgba(102, 122, 181, 0.79)"
ButtonActive = "rgba(117, 137, 204, 1.0)"
Header = "rgba(102, 102, 229, 0.45)"
HeaderHovered = "rgba(114, 114, 229, 0.8)"
HeaderActive = "rgba(135, 135, 221, 0.8)"
Separator = "rgba(127, 127, 127, 0.6)"
SeparatorHovered = "rgba(153, 153, 178, 1.0)"
SeparatorActive = "rgba(178, 178, 229, 1.0)"
ResizeGrip = "rgba(255, 255, 255, 0.1)"
ResizeGripHovered = "rgba(198, 209, 255, 0.6)"
ResizeGripActive = "rgba(198, 209, 255, 0.9)"
Tab = "rgba(85, 85, 174, 0.786)"
TabHovered = "rgba(114, 114, 229, 0.8)"
TabActive = "rgba(103, 103, 185, 0.842)"
TabUnfocused = "rgba(72, 72, 145, 0.8212)"
TabUnfocusedActive = "rgba(89, 89, 166, 0.8372)"
PlotLines = "rgba(255, 255, 255, 1.0)"
PlotLinesHovered = "rgba(229, 178, 0, 1.0)"
PlotHistogram = "rgba(229, 178, 0, 1.0)"
PlotHistogramHovered = "rgba(255, 153, 0, 1.0)"
TableHeaderBg = "rgba(68, 68, 96, 1.0)"
TableBorderStrong = "rgba(79, 79, 114, 1.0)"
TableBorderLight = "rgba(66, 66, 71, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.07)"
TextSelectedBg = "rgba(0, 0, 255, 0.35)"
DragDropTarget = "rgba(255, 255, 0, 0.9)"
NavHighlight = "rgba(114, 114, 229, 0.8)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.7)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2)"
ModalWindowDimBg = "rgba(51, 51, 51, 0.35)"