# Comfortable Light Orange style by SouthCraftX from ImThemes
alpha = 1.0
disabledAlpha = 1.0
windowPadding = [20.0, 20.0]
windowRounding = 11.5
windowBorderSize = 0.0
windowMinSize = [20.0, 20.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "None"
childRounding = 20.0
childBorderSize = 1.0
popupRounding = 17.4
popupBorderSize = 1.0
framePadding = [20.0, 3.4]
frameRounding = 11.9
frameBorderSize = 0.0
itemSpacing = [8.9, 13.4]
itemInnerSpacing = [7.1, 1.8]
cellPadding = [12.1, 9.2]
indentSpacing = 0.0
columnsMinSpacing = 8.7
scrollbarSize = 11.6
scrollbarRounding = 15.9
grabMinSize = 3.7
grabRounding = 20.0
tabRounding = 9.8
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(0, 0, 0, 1.0)"
TextDisabled = "rgba(185, 174, 140, 1.0)"
WindowBg = "rgba(235, 233, 229, 1.0)"
ChildBg = "rgba(231, 229, 225, 1.0)"
PopupBg = "rgba(235, 233, 229, 1.0)"
Border = "rgba(215, 212, 206, 1.0)"
BorderShadow = "rgba(235, 233, 229, 1.0)"
FrameBg = "rgba(226, 223, 216, 1.0)"
FrameBgHovered = "rgba(215, 212, 206, 1.0)"
FrameBgActive = "rgba(215, 212, 206, 1.0)"
TitleBg = "rgba(243, 241, 237, 1.0)"
TitleBgActive = "rgba(243, 241, 237, 1.0)"
TitleBgCollapsed = "rgba(235, 233, 229, 1.0)"
MenuBarBg = "rgba(230, 228, 224, 1.0)"
ScrollbarBg = "rgba(243, 241, 237, 1.0)"
ScrollbarGrab = "rgba(225, 221, 217, 1.0)"
ScrollbarGrabHovered = "rgba(215, 212, 206, 1.0)"
ScrollbarGrabActive = "rgba(225, 221, 217, 1.0)"
CheckMark = "rgba(247, 13, 40, 1.0)"
SliderGrab = "rgba(246, 204, 7, 1.0)"
SliderGrabActive = "rgba(247, 150, 9, 1.0)"
Button = "rgba(225, 221, 217, 1.0)"
ButtonHovered = "rgba(209, 207, 205, 1.0)"
ButtonActive = "rgba(216, 216, 216, 1.0)"
Header = "rgba(219, 213, 202, 1.0)"
HeaderHovered = "rgba(228, 228, 228, 1.0)"
HeaderActive = "rgba(235, 233, 229, 1.0)"
Separator = "rgba(222, 217, 206, 1.0)"
SeparatorHovered = "rgba(215, 208, 191, 1.0)"
SeparatorActive = "rgba(215, 208, 191, 1.0)"
ResizeGrip = "rgba(218, 218, 218, 1.0)"
ResizeGripHovered = "rgba(247, 13, 40, 1.0)"
ResizeGripActive = "rgba(0, 0, 0, 1.0)"
Tab = "rgba(235, 233, 229, 1.0)"
TabHovered = "rgba(225, 221, 217, 1.0)"
TabActive = "rgba(225, 221, 217, 1.0)"
TabUnfocused = "rgba(235, 233, 229, 1.0)"
TabUnfocusedActive = "rgba(223, 185, 109, 1.0)"
PlotLines = "rgba(122, 102, 76, 1.0)"
PlotLinesHovered = "rgba(245, 5, 30, 1.0)"
PlotHistogram = "rgba(231, 169, 79, 1.0)"
PlotHistogramHovered = "rgba(163, 101, 11, 1.0)"
TableHeaderBg = "rgba(243, 241, 237, 1.0)"
TableBorderStrong = "rgba(243, 241, 237, 1.0)"
TableBorderLight = "rgba(255, 255, 255, 1.0)"
TableRowBg = "rgba(225, 221, 217, 1.0)"
TableRowBgAlt = "rgba(230, 228, 224, 1.0)"
TextSelectedBg = "rgba(16, 16, 16, 1.0)"
DragDropTarget = "rgba(128, 124, 0, 1.0)"
NavHighlight = "rgba(187, 181, 0, 1.0)"
NavWindowingHighlight = "rgba(128, 124, 0, 1.0)"
NavWindowingDimBg = "rgba(205, 210, 116, 0.502)"
ModalWindowDimBg = "rgba(205, 210, 116, 0.502)"
